# Generated by Django 4.2.16 on 2025-05-23 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="is_face_registered",
            field=models.BooleanField(default=False),
        ),
    ]
