# Generated by Django 4.2.16 on 2025-05-24 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0002_student_is_face_registered"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="timestamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
