# Generated by Django 4.2.16 on 2025-05-24 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0003_alter_attendance_date_alter_attendance_timestamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
